# Generated by Django 3.2.25 on 2025-11-11 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangalib', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_admin', models.CharField(max_length=25)),
                ('email_admin', models.EmailField(max_length=25, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pack_service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_pack', models.CharField(max_length=25, unique=True)),
                ('Descript_pack', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='produits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_product', models.CharField(max_length=30, unique=True)),
                ('type', models.CharField(max_length=30)),
                ('quantity', models.IntegerField()),
                ('prix', models.IntegerField()),
                ('descript_product', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('physic_adress_user', models.CharField(max_length=25)),
                ('email_user', models.EmailField(max_length=25, unique=True)),
                ('tel_user', models.IntegerField(unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='books',
            name='Author',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='books',
        ),
    ]
