# Generated by Django 3.2.25 on 2025-11-12 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mangalib', '0002_auto_20251111_1747'),
    ]

    operations = [
        migrations.DeleteModel(
            name='admin',
        ),
        migrations.DeleteModel(
            name='users',
        ),
    ]
