# Generated by Django 3.2.25 on 2025-11-12 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangalib', '0003_auto_20251112_0156'),
    ]

    operations = [
        migrations.CreateModel(
            name='services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_service', models.CharField(max_length=30, unique=True)),
                ('type_service', models.CharField(max_length=30)),
                ('prix_service', models.IntegerField()),
                ('descript_service', models.CharField(max_length=255)),
            ],
        ),
    ]
