# Generated by Django 3.2.25 on 2025-11-15 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangalib', '0004_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('physic_adress_user', models.CharField(max_length=25)),
                ('email_user', models.EmailField(max_length=25, unique=True)),
                ('tel_user', models.IntegerField(unique=True)),
            ],
        ),
    ]
