# Generated by Django 3.2.25 on 2025-11-15 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangalib', '0005_users'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name': 'utlisateur', 'verbose_name_plural': 'utlisateurs'},
        ),
        migrations.AlterField(
            model_name='pack_service',
            name='Descript_pack',
            field=models.CharField(max_length=255, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='pack_service',
            name='title_pack',
            field=models.CharField(max_length=25, unique=True, verbose_name='Titre'),
        ),
        migrations.AlterField(
            model_name='produits',
            name='descript_product',
            field=models.CharField(max_length=255, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='produits',
            name='prix',
            field=models.IntegerField(verbose_name='Prix'),
        ),
        migrations.AlterField(
            model_name='produits',
            name='quantity',
            field=models.IntegerField(verbose_name='Quantite'),
        ),
        migrations.AlterField(
            model_name='produits',
            name='title_product',
            field=models.CharField(max_length=30, unique=True, verbose_name='Titre'),
        ),
        migrations.AlterField(
            model_name='produits',
            name='type',
            field=models.CharField(max_length=30, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='services',
            name='descript_service',
            field=models.CharField(max_length=255, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='services',
            name='prix_service',
            field=models.IntegerField(verbose_name='Prix'),
        ),
        migrations.AlterField(
            model_name='services',
            name='title_service',
            field=models.CharField(max_length=30, unique=True, verbose_name='Titre'),
        ),
        migrations.AlterField(
            model_name='services',
            name='type_service',
            field=models.CharField(max_length=30, verbose_name='Type de service'),
        ),
        migrations.AlterField(
            model_name='users',
            name='email_user',
            field=models.EmailField(max_length=25, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='users',
            name='name',
            field=models.CharField(max_length=25, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='users',
            name='physic_adress_user',
            field=models.CharField(max_length=25, verbose_name='Adresse physique'),
        ),
        migrations.AlterField(
            model_name='users',
            name='tel_user',
            field=models.IntegerField(unique=True, verbose_name='Contact'),
        ),
    ]
