# Generated by Django 3.2.25 on 2025-11-15 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangalib', '0006_auto_20251115_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='pack_service',
            name='Price',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
