# Generated by Django 3.2.25 on 2025-11-15 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangalib', '0007_pack_service_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pack_service',
            name='Price',
            field=models.IntegerField(verbose_name='prix'),
        ),
    ]
