# Generated by Django 5.2.8 on 2025-11-26 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mangalib", "0008_alter_pack_service_price"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="users",
            options={
                "verbose_name": "utilisateur",
                "verbose_name_plural": "utilisateurs",
            },
        ),
    ]
